dev: true
http:
  host: 127.0.0.1
  port: 30233
  session:
    key: key
    expires: 30
db:
  host: 127.0.0.1
  port: 27017
  db: db
  user: user
  password: password
redis:
  host: 127.0.0.1
  port: 6379
  password: password
  db: 0
violet:
  id: 5cd999e153b5735e91249c3b5
  key: viu26hpfee8cxfaykmrea4
  host: https://example.com/api
  callback: https://my.website.com/auth
