### 获取登陆链接
GET http://127.0.0.1:30233/session

### 登陆
GET http://127.0.0.1:30233/session/violet?code=8f48c80107e95a232629c7301f3ac3300eb4220dbf7b38a373dfec4ffd07cee59a286576532e004ea20739b68a80cd8763bfa2111725728c879da6dadbadc5df6edc6ec47717a0edee13c2264e29160fe58b312dcb531c1d228f7cd6bcd3f824d8&state=9b3291d1427aa3d43a6738da6ed2e5c966d962f9d1b96002a2d2

### 获取登陆状态
// GET http://127.0.0.1:30233/session/status
https://coin.zhenly.cn/api/session/status

### 获取用户信息
GET http://127.0.0.1:30233/users/info/me
//GET https://coin.zhenly.cn/api/users/info/me


### 获取用户信息
GET http://127.0.0.1:30233/users/info/5cf6588cf629d9be71a64875

### 签到
POST http://127.0.0.1:30233/users/attend

### 修改资料
PUT http://127.0.0.1:30233/users/info
Content-Type: application/json

{
  "nickname": "BBShow🐷"
}

### 修改用户类型
PUT http://127.0.0.1:30233/users/type
Content-Type: application/json

{
  "id": "5cdbf6fe678405360d9fc162",
  "type": "normal"
}

### 微信登陆
// POST http://127.0.0.1:30233/session/wechat
POST  http://127.0.0.1:30233/session/wechat
Content-Type: application/json

{
  "code": "043EMBGb19k3Vv0Ns8Ib1OOUGb1EMBGL"
}

### 微信二维码
GET http://127.0.0.1:30233/session/wechat

### 用户认证
POST http://127.0.0.1:30233/certification
Content-Type: application/json

{
  "identity": "student",
  "data": "我是秀秀",
  "type": "email",
  "email": "zhenlychen@foxmail.com"
}

### 用户认证
GET http://127.0.0.1:30233/certification/auth?code=0182949eef78757e93c7bb2deea32b88613b12d0c0629ed5632915fc031816fbc436285da10a674eeaeb797e7c312fb46418d3030ce34676cf0855825d6f081e&user=5cf6588cf629d9be71a64875

### 新建任务
POST http://127.0.0.1:30233/tasks
Content-Type: application/json

{
  "title": "睡觉",
  "content": "到底什么时候睡觉啊",
  "type": "run",
  "reward": "object",
  "reward_object": "觉",
  "location": [
    "床上"
  ],
  "tags": [
    "睡觉"
  ],
  "start_date": 1579797713,
  "end_date": 1579797724,
  "max_player": 2,
  "auto_accept": true,
  "publish": false
}

### 获取任务列表
// GET http://127.0.0.1:30233/tasks?page=1&size=10
Get https://coin.zhenly.cn/api/tasks?page=1&size=10

### 获取单个任务详情
GET http://127.0.0.1:30233/tasks/5cfba56596a3b91b06b6dc3e

### 修改任务信息

PUT http://127.0.0.1:30233/tasks/5cfba56596a3b91b06b6dc3e
Content-Type: application/json

{
  "tags": ["起床", "睡觉"]
}

### 删除任务
DELETE http://127.0.0.1:30233/tasks/5cfbcb2836ef7fc31418d916

### 添加阅读量
POST http://127.0.0.1:30233/tasks/5cfba56596a3b91b06b6dc3e/view

### 任务点赞
POST http://127.0.0.1:30233/tasks/5cfba56596a3b91b06b6dc3e/like

### 取消点赞
DELETE http://127.0.0.1:30233/tasks/5cfba56596a3b91b06b6dc3e/like

### 获取评论列表
GET http://127.0.0.1:30233/comments/5cfba56596a3b91b06b6dc3e

### 添加评论
POST http://127.0.0.1:30233/comments/5cfba56596a3b91b06b6dc3e
Content-Type: application/json

{
  "type": "task",
  "content": "这是第二条评论哦🐷"
}

### 添加回复
POST http://127.0.0.1:30233/comments/5cfcac1d899659486b1ac02b
Content-Type: application/json

{
  "type": "comment",
  "content": "这是一个回复哦❤"
}

### 删除评论/回复
DELETE http://127.0.0.1:30233/comments/5cfcac1d899659486b1ac02b

### 点赞评论/回复
POST http://127.0.0.1:30233/comments/5cfcab061a9341e1cb5e1ca7/like

### 删除点赞评论/回复
DELETE http://127.0.0.1:30233/comments/5cfcab061a9341e1cb5e1ca7/like
